apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  selector:
    matchLabels:
      run: web-app
  replicas: 2
  template:
    metadata:
      labels:
        run: web-app
    spec:
      containers:
      - name: web-app
        image: ssuwani/mnist_web-app
        ports:
        - containerPort: 80

