apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
nameSuffix: "-"
images:
  - name: ghcr.io/ssuwani/train-mnist
    newTag: 0.0.16

patches:
  - path: train-job-patch.json
    target:
      group: batch
      kind: Job
      name: mnist-train-job
      version: v1
