apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-train-job
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
      - name: mnist-classifier-trainig
        image: ghcr.io/ssuwani/train-mnist:0.0.1
        args: ["--epochs", "1"]

      restartPolicy: Never